### PR TITLE
Unittesting

### PR DESCRIPTION
**Pull request by NathanaelA**
This adds the unit testing to the framework.  We were waiting on the main repo to have the changes before we could run the unit tests here.  Main repo was updated a couple weeks ago; double checked that the testing harness now works properly, from a fresh clone.

### CODE REVIEW

**Comment by mattheworiordan** [comment]
@NathanaelA is it not possible to run the tests via Travis?  We run Android tests currently via Travis so expect it's possible.  What's involved in that?

**Comment by NathanaelA** [comment]
I believe you can run tests via Travis; since this is just a normal android app. 
Basically to do this your steps are:
1. npm install nativescript@2.5.4 -g
2. Clone this repo.   
3. Chdir into the demo-unittesting
4. tns install
5. tns build android
6. tns test android

**Comment by mattheworiordan** [comment]
> Basically to do this your steps are:

Sorry, I am not sure I follow you.  The point of Travis is to run this automatically.  So we need a Travis.yml file like https://github.com/ably/ably-js/blob/master/.travis.yml or https://github.com/ably/ably-java/blob/master/.travis.yml so that the tests are run automatically and results pushed back into Github.

**Comment by NathanaelA** [comment]
I was giving you the steps for who ever needs to setup the Travis -- I was assuming you would want to deal with this internally to save money as we are already up over the projected hours...   

However, if you want me to do it I can, I never turn down paid work.  :grinning:    I was just trying to save you some money, by giving you all the steps that needed to occur to build the test app to run the test bed...

**Comment by mattheworiordan** [comment]
> I was giving you the steps for who ever needs to setup the Travis -- I was assuming you would want to deal with this internally to save money as we are already up over the projected hours...

Seems odd to me to go 99% of the way in terms of adding a test suite, and then not actually integrate the test suite no?

> However, if you want me to do it I can, I never turn down paid work. 😀 I was just trying to save you some money, by giving you all the steps that needed to occur to build the test app to run the test bed...

Let's not debate money in Github!  A test suite and CI was always part of the expectation otherwise I see little point in adding tests in the first place.

**Comment by NathanaelA** [comment]
I apologize for any miscommunications and assumptions on my part.   To be honest I was unaware of any CI requirement until you mentioned it now in this thread.    Your request to me was for the ability to run your nodeunit tests in the NativeScript environment.    Travis was never mentioned in any of our emails, so when you mentioned it here; I was trying to give you the info you needed to integrate what I did into Travis as I made the "assumption" you just needed to know the build steps on how to get it working.   

As I stated earlier I have no issues getting it working in Travis; it just was not part of any expectation that I was made aware of, so I honestly didn't want to just jump on doing this (something I perceived as extra) without your implicit consent.    

I will attempt to get Travis integration working by this weekend, hopefully I can squeeze the time in.  ;-)

**Comment by NathanaelA** [comment]
I have finally had the time to finish the travis integration.  Merging this #4 with #5 will give you the the full travis support.  (Tested on my own local repo because I needed full rights, so unfortunately it has to be a second pull request from my repo).

However, Travis only seems to be able to run the first 24 or so test before it totally times out.  Some of this appears to be changes to ably since I last worked on the integration testing.  I'm not sure if there is some change that broke things in the main library; but it appears to be attempting to do XHR tests and timing out on them when Simon had disable them in the main repo for NativeScript.  So there maybe some sort of issue with something not being in sync...

The other possibility is that maybe my travis wasn't picking up this pull request which fixes a lot of the testing issues and so I was just getting the travis support.   Hard to say, not real clear in this case since it considered it two separate pull requests...

**Pull request closed without merging**
